// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT2mYOQdtGVQAlZtlzSI0vHjvX0710IdE',
    appId: '1:879416275075:web:5285a4dfa72bcfbf11abb6',
    messagingSenderId: '879416275075',
    projectId: 'scan2win-49bf9',
    authDomain: 'scan2win-49bf9.firebaseapp.com',
    storageBucket: 'scan2win-49bf9.firebasestorage.app',
    measurementId: 'G-WRJ2SCVZEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtBQkO1Z2KhdBxw2ZVUs6pw-oZ1n0-pWg',
    appId: '1:879416275075:android:7c60e175f6cbebef11abb6',
    messagingSenderId: '879416275075',
    projectId: 'scan2win-49bf9',
    storageBucket: 'scan2win-49bf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArWaL-8rpyNY2T46Eoi9cZHhGiNTNrYWA',
    appId: '1:879416275075:ios:dfce56c5ea5847e211abb6',
    messagingSenderId: '879416275075',
    projectId: 'scan2win-49bf9',
    storageBucket: 'scan2win-49bf9.firebasestorage.app',
    iosBundleId: 'com.example.scan2win',
  );
}
